
trigger: none

variables:
- name: TeamName
  value: AzureDiagnostics

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
  
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
    
    stages:
    - stage: Build
      
      jobs:
      - job: Core_Build
        displayName: Core Build
        pool:
          name: AzurePipelines-EO
          image: 1ESPT-Windows2022
        
        steps:

        - checkout: self
          clean: true

        - task: BatchScript@1
          displayName: Setup build environment
          inputs:
            filename: '$(Build.SourcesDirectory)\tools\setEnv.cmd'
            modifyEnvironment: true

        - task: BatchScript@1
          displayName: Restore nuget packages
          inputs:
            filename: $(Build.SourcesDirectory)\tools\restore.cmd
            modifyEnvironment: true

        - task: DotNetCoreCLI@2
          displayName: Build solution
          inputs:
            projects: $(Build.SourcesDirectory)\Warsaw.sln
            arguments: '--configuration Release --verbosity minimal -bl:$(Build.SourcesDirectory)\binlogs\msbuild.binlog'

        - task: BatchScript@1
          displayName: Run tests
          inputs:
              filename: $(Build.SourcesDirectory)\tools\runtest.cmd
              modifyEnvironment: false

        - task: PowerShell@2
          displayName: Create NuGet packages
          inputs:
            filePath: $(Build.SourcesDirectory)\tools\createNugetPackages.ps1

        - task: 1ES.PublishPipelineArtifact@1
          displayName: Publish binary build logs
          inputs:
            targetPath: $(Build.SourcesDirectory)\binlogs
            artifactName: binlogs
